
package put.poznan.estudent;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthenticationServiceService", targetNamespace = "http://estudent.poznan.put/", wsdlLocation = "http://localhost:8081/eStudent/authenticationService?wsdl")
public class AuthenticationServiceService
    extends Service
{

    private final static URL AUTHENTICATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATIONSERVICESERVICE_EXCEPTION;
    private final static QName AUTHENTICATIONSERVICESERVICE_QNAME = new QName("http://estudent.poznan.put/", "AuthenticationServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/eStudent/authenticationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATIONSERVICESERVICE_WSDL_LOCATION = url;
        AUTHENTICATIONSERVICESERVICE_EXCEPTION = e;
    }

    public AuthenticationServiceService() {
        super(__getWsdlLocation(), AUTHENTICATIONSERVICESERVICE_QNAME);
    }

    public AuthenticationServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATIONSERVICESERVICE_QNAME, features);
    }

    public AuthenticationServiceService(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATIONSERVICESERVICE_QNAME);
    }

    public AuthenticationServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATIONSERVICESERVICE_QNAME, features);
    }

    public AuthenticationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthenticationWebService
     */
    @WebEndpoint(name = "AuthenticationServicePort")
    public AuthenticationWebService getAuthenticationServicePort() {
        return super.getPort(new QName("http://estudent.poznan.put/", "AuthenticationServicePort"), AuthenticationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationWebService
     */
    @WebEndpoint(name = "AuthenticationServicePort")
    public AuthenticationWebService getAuthenticationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://estudent.poznan.put/", "AuthenticationServicePort"), AuthenticationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATIONSERVICESERVICE_EXCEPTION!= null) {
            throw AUTHENTICATIONSERVICESERVICE_EXCEPTION;
        }
        return AUTHENTICATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
