
package put.poznan.estudent;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationWebService", targetNamespace = "http://estudent.poznan.put/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationWebService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns put.poznan.estudent.AuthenticationResult
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://estudent.poznan.put/AuthenticationWebService/authenticateRequest", output = "http://estudent.poznan.put/AuthenticationWebService/authenticateResponse")
    public AuthenticationResult authenticate(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

}
